serveer.port=4433
spring.application.name=redis-with-spring-boot

spring.redis.host=localhost
spring.redis.port=6379

openweathermap.api.key=H5rxLOAAPrsMjCvYqa3gngANS7t26pq6
openweathermap.api.url=https://api.tomorrow.io/v4/weather/realtime
#curl --request GET --url 'https://api.tomorrow.io/v4/weather/forecast?location=42.3478,-71.0466&apikey=v0pd0nnjOPrQyQTMUiJRgX0glxmDkfhw'
#curl --request GET --url 'https://api.tomorrow.io/v4/weather/forecast?location=new%20york&apikey=v0pd0nnjOPrQyQTMUiJRgX0glxmDkfhw' --compressed --header 'accept: application/json' --header 'accept-encoding: deflate, gzip, br'